[project]
name = "langchain-course"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "black>=25.9.0",
    "isort>=6.0.1",
    "langchain[openai]>=0.3.27",
    "langchain-openai>=0.3.33",
    "langgraph>=0.6.7",
    "python-dotenv>=1.1.1",
    "langchain-tavily>=0.2.11",
    "langchain-pinecone>=0.2.12",
    "langchainhub>=0.1.21",
    "langchain-community>=0.3.31",
    "pypdf>=6.1.1",
    "faiss-cpu>=1.12.0",
    "beautifulsoup4>=4.14.2",
    "tiktoken>=0.11.0",
    "openai>=1.108.1",
    "unstructured>=0.18.15",
    "nltk>=3.9.2",
    "fastapi>=0.119.0",
    "jinja2>=3.1.6",
    "uvicorn>=0.37.0",
    "streamlit>=1.50.0",
    "streamlit-chat>=0.1.1",
    "tqdm>=4.67.1",
    "firecrawl-py>=4.3.7",
    "langsmith>=0.4.29",
    "pillow>=11.3.0",
    "certifi>=2025.8.3",
    "langchain-chroma>=0.2.6",
    "langchain-experimental>=0.3.4",
    "qrcode>=8.2",
    "pandas>=2.3.3",
    "tabulate>=0.9.0",
]

[dependency-groups]
dev = [
    "ipykernel>=6.30.1",
]
